### PR TITLE
chore: use node8 for building

### PR DESCRIPTION
**Pull request by FenrirUnbound**
## Context

Node 8 was released on May 30th! https://nodejs.org/en/blog/release/v8.0.0/

## Objective

Use Node 8 to build `scm-base`

## References

* https://nodejs.org/en/blog/release/v8.0.0/

### CODE REVIEW

**Comment by r3rastogi** [comment]
What is the point of a `package-lock.json` file, and how did you generate it?

**Comment by FenrirUnbound** [comment]
> What is the point of a package-lock.json file, and how did you generate it?

* http://blog.npmjs.org/post/161081169345/v500
* https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by FenrirUnbound** [comment]
It's equivalent to a `Gemfile.lock` file

**Comment by d2lam** [comment]
@FenrirUnbound  `chore` won't publish a new version with `semantic-release`. It's okay to leave it and when next change comes, `semantic-release` will pick it up. If you want it to be published now, you would need to make another commit with a `fix`.

**Pull request merged**
